ALTER TABLE public.daily_leads
  ADD COLUMN IF NOT EXISTS aa integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ca integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ne integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS propuesta integer NOT NULL DEFAULT 0;